# Generated by Django 5.0.6 on 2024-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
